---
title: "HOWTO: Using the SEFSC Quarto Theme"
subtitle: Creating your own documentation page using the SEFSC Quarto Theme
order: 2
---

The [SEFSC-documentation-quarto-skeleton](https://github.com/MattGrossi-NOAA/SEFSC-documentation-quarto-skeleton) repository is a template, or "skeleton", starting point to create a new GitHub-based documentation site that uses the NOAA Fisheries Southeast Fisheries Science Center (SEFSC) [documentation-theme-quarto](https://github.com/MattGrossi-NOAA/documentation-theme-quarto) documentation format and functionality. This documentation theme is derived from the NOAA Fisheries Open Science [NOAA-quarto-simple-python](https://github.com/nmfs-opensci/NOAA-quarto-simple-python) repository and is inspired by the Integrated Ocean Observing System (IOOS) [documentation-theme-jekyll](https://github.com/ioos/documentation-theme-jekyll), which is used for all [https://ioos.github.io](https://ioos.github.io) sites.

The instructions below will allow you to create a new GitHub Pages site that follows the look and feel/functionality of the documentation theme used by the [https://ioos.github.io](https://ioos.github.io) site. You can then add/edit the template markdown documents with your own content.

The theme has many additional features that have are not demonstrated nor utilized in this preview repository. Check out the [Quarto documentation](https://quarto.org/docs/websites/) to learn more.

## Preliminaries

This Quarto website has Python code in the `code.qmd` file and has a Jupyter notebook. The GitHub Action will render those for you but note that you need some a special **RAW** block at the top of your ipynb file. Without this, the Jupyter notebook won't render (code blocks won't be computed). It looks like this
```
---
title: Jupyter Notebook
execute:
  enabled: true
jupyter: python3
---
```
Also you will need to add any modules that your code needs to the `requirements.txt` file so they are installed by the GitHub Action.
